spring.datasource.url=jdbc:postgresql://ep-late-block-anduyr5j-pooler.c-6.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_F3lQqLxpA4aU&sslmode=require&channelBinding=require
spring.jpa.hibernate.ddl-auto=update

spring.freemarker.suffix=.ftlh
spring.freemarker.template-loader-path=classpath:/templates/

#Log out sql queries or comment these lines out with a hashtag
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.hibernate.orm.jdbc.bind=TRACE